<a href="https://colab.research.google.com/github/Sankha1998/machine_learning/blob/master/Implement_Logistic_Regression_Model_with_L1_and_L2_Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("dataset.txt")

In [3]:
data.head()

Marks_1    Marks_2  Result
0  34.623660  78.024693       0
1  30.286711  43.894998       0
2  35.847409  72.902198       0
3  60.182599  86.308552       1
4  79.032736  75.344376       1

In [4]:
x = np.array(data.iloc[:,:2].values)
y = np.array(data.iloc[:,-1].values)

In [5]:
y

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [74]:
def fit(x, y): ## for lasso 
  lr = 0.001 
  iteration = 100000
  n, n_features = x.shape  
  w = np.zeros(n_features)
  b = 0
  lambd_a = 100
  for _ in range(iteration):
      p=(lambd_a/(2*n)*sum(w)) ## updated cost function
      eq = (np.dot(x, w) + b) + p

      y_pred = 1 / (1 + np.exp(-eq)) ##sigmoid

      wbar = (1 / n) * np.dot(x.T, (y_pred - y)) 
      bbar = ((1 / n) * np.sum(y_pred - y))
    
      w = w -(lr * wbar)
      b = b - (lr * bbar)
  return (w,b)

In [75]:
 w,b=fit(x, y)

In [76]:
def predict(x_t):
 
  w,b=fit(x, y)
  e = np.dot(x_t,w) + b 
  y_pred = 1 / (1 + np.exp(-e))
  y_cls = [1 if i > 0.5 else 0 for i in y_pred]
  return np.array(y_cls)

In [77]:
h = np.array([[34.62366 , 78.024693]])

In [78]:
predict(h)

array([0])

In [79]:
h = np.array([[79.032736 ,	175.344376]])

In [80]:
predict(h)

array([1])

In [86]:
def fit(x, y): ## for ridge
  lr = 0.001 
  iteration = 100000
  n, n_features = x.shape  
  w = np.zeros(n_features)
  b = 0
  lambd_a = 100
  for _ in range(iteration):
      p=(lambd_a/(2*n)*sum(w**2)) ## updated cost function
      eq = (np.dot(x, w) + b) + p

      y_pred = 1 / (1 + np.exp(-eq)) ##sigmoid

      wbar = (1 / n) * np.dot(x.T, (y_pred - y)) 
      bbar = ((1 / n) * np.sum(y_pred - y))
    
      w = w -(lr * wbar)
      b = b - (lr * bbar)
  return (w,b)

In [87]:
def predict(x_t):
 
  w,b=fit(x, y)
  e = np.dot(x_t,w) + b 
  y_pred = 1 / (1 + np.exp(-e))
  y_cls = [1 if i > 0.5 else 0 for i in y_pred]
  return np.array(y_cls)

In [110]:
h= 	np.array([[35.847409,72.902198]])

In [89]:
predict(h)

array([0])

In [90]:
data.tail()

Marks_1    Marks_2  Result
95  83.489163  48.380286       1
96  42.261701  87.103851       1
97  99.315009  68.775409       1
98  55.340018  64.931938       1
99  74.775893  89.529813       1

In [113]:
h = np.array(data.iloc[-1,[0,1]].values).reshape(1,2)

In [115]:
h

array([[74.775893 , 89.5298129]])

In [116]:
predict(h)

array([1])