<a href="https://colab.research.google.com/github/Sankha1998/machine_learning/blob/master/Logistic_Regression_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np


In [21]:
data = pd.read_csv("dataset.txt")

In [22]:
data.head()

Marks_1    Marks_2  Result
0  34.623660  78.024693       0
1  30.286711  43.894998       0
2  35.847409  72.902198       0
3  60.182599  86.308552       1
4  79.032736  75.344376       1

In [24]:
x = np.array(data.iloc[:,:2].values)
y = np.array(data.iloc[:,-1].values)

In [25]:
y

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [96]:
def fit(x, y):
  lr = 0.001 
  iteration = 100000
  n, n_features = x.shape  
  w = np.zeros(n_features)
  b = 0
  for _ in range(iteration):
      eq = np.dot(x, w) + b

      y_pred = 1 / (1 + np.exp(-eq)) ##sigmoid

      wbar = (1 / n) * np.dot(x.T, (y_pred - y))
      bbar = (1 / n) * np.sum(y_pred - y)
    
      w = w -(lr * wbar)
      b = b - (lr * bbar)
  return (w,b)

In [97]:

def predict(x_t):
  w,b=fit(x, y)
  e = np.dot(x_t,w) + b
  y_pred = 1 / (1 + np.exp(-e))
  y_cls = [1 if i > 0.5 else 0 for i in y_pred]
  return np.array(y_cls)

In [98]:
h = np.array([[34.62366 , 78.024693]])

In [99]:
predict(h)

array([0])

In [100]:
h = np.array([[79.032736 ,	175.344376]])

In [101]:
predict(h)

array([1])